# Server
server.port=8080

spring.data.mongodb.uri=mongodb+srv://minnhtunsan2_db_user:6EAyo7JxUiz0QKLQ@cluster0.ecdzwu5.mongodb.net/royal_classico_db?retryWrites=true&w=majority&connectTimeoutMS=30000
spring.data.mongodb.database=royal_classico_db
# Ensure standard UUID representation to avoid driver mismatches
spring.data.mongodb.uuid-representation=standard

# If using embedded Mongo for tests/dev, disable embedded storage to avoid startup interference
spring.mongodb.embedded.storage.enabled=false

# Devtools: if spring-boot-devtools is present, disable automatic restart for stability during manual runs
spring.devtools.restart.enabled=false

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- ADD THESE IMAGEKIT CLOUD KEYS HERE ---
imagekit.publicKey=public_LaJbzOC98dTm3SkWMaIl2a0sTAA=
imagekit.privateKey=private_FA6xRKMfLxrP5+SWuK7WQDukE1E=
imagekit.urlEndpoint=https://ik.imagekit.io/sanminnhtun


# Admin Secret Header
app.admin.secret=RC_SECRET_2026

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Static resources - WE ONLY NEED STATIC NOW (No more local uploads folder)
spring.web.resources.static-locations=classpath:/static/